/* Replace with your SQL commands */

INSERT INTO `dessert` (`name`, `photo`) VALUES ('Banoffee ', 'https://www.savingdessert.com/wp-content/uploads/2015/08/Banoffee-Pie-11-800x533.jpg');
INSERT INTO `dessert` (`name`, `photo`) VALUES ('Ile Flottante', 'https://static.750g.com/images/640-420/2496d66435941250b6215b787bf4d294/ile-flottante-facile.jpg');
INSERT INTO `dessert` (`name`, `photo`) VALUES ('Tiramisu', 'https://www.galbani.fr/wp-content/uploads/2017/07/le_veritable_tiramisu_par_il_gusto_italiano_0.png');
INSERT INTO `dessert` (`name`, `photo`) VALUES ('Fondant au chocolat', 'https://assets.afcdn.com/recipe/20170614/69595_w1024h576c1cx2000cy3000.webp');
INSERT INTO `dessert` (`name`, `photo`) VALUES ('Tarte aux pommes', 'https://static.750g.com/images/1200-630/c466db31c600e66b9ec6ccef054119e2/tarte-aux-pommes-amandes.jpg');
INSERT INTO `dessert` (`name`, `photo`) VALUES ('Cheesecake fruits rouges', 'https://www.pazapah.fr/wp-content/uploads/2020/04/P1533803-min-scaled.jpg');
INSERT INTO `dessert` (`name`, `photo`) VALUES ('Baba au rhum', 'https://img-3.journaldesfemmes.fr/BP9M7xUH77r5O5S-KlLLNDpPa8Q=/750x/smart/179461a343fe4338a409054ccec961b5/recipe-jdf/382986.jpg');
INSERT INTO `dessert` (`name`, `photo`) VALUES ('Tarte à la framboise', 'https://img.cuisineaz.com/660x660/2013-12-20/i16627-tarte-aux-framboises-et-chantilly.jpg');
INSERT INTO `dessert` (`name`, `photo`) VALUES ('Eclairs au chocolat', 'https://www.eismann.fr/content/images/thumbs/0002387_eclairs-au-chocolat_550.jpeg');
INSERT INTO `dessert` (`name`, `photo`) VALUES ('Tarte au citron', 'https://wordpress.potagercity.fr/wp-content/uploads/2019/04/tarte_citron_meringuee.jpg');
INSERT INTO `dessert` (`name`, `photo`) VALUES ('Paris Brest', 'https://cache.marieclaire.fr/data/photo/w600_h315_ci/5b/paris-brest-traditionnel.jpg');
INSERT INTO `dessert` (`name`, `photo`) VALUES ('Crumble aux pommes', 'https://static.750g.com/images/1200-630/4c49cd428d0e6942c790044bbfbeb24a/crumble-aux-pommes.jpg');
INSERT INTO `dessert` (`name`, `photo`) VALUES ('Profiteroles', 'https://www.latableadessert.fr/sites/default/files/styles/mega_fiche/public/images/recipe/field_recipe_single_carousel_img/recette-profiteroles_12121.jpg?itok=CSoOozfI');
INSERT INTO `dessert` (`name`, `photo`) VALUES ('Clafoutis pruneaux ', 'https://cac.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2FCAC.2F2019.2F09.2F20.2Fd4caeaca-765b-429b-8125-29eb2b58d5d6.2Ejpeg/865x600/quality/65/clafoutis-aux-pruneaux.jpg');
INSERT INTO `dessert` (`name`, `photo`) VALUES ('Cupcake fraise', 'https://cac.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2FCAC.2F2019.2F09.2F20.2F9d63127e-0aa3-4865-9dc9-b50a9cdf04a4.2Ejpeg/865x600/quality/65/cupcake-a-la-fraise.jpg');

INSERT INTO `difficulty` (`name`) VALUES ('Très facile');
INSERT INTO `difficulty` (`name`) VALUES ('Facile');
INSERT INTO `difficulty` (`name`) VALUES ('Moyen');
INSERT INTO `difficulty` (`name`) VALUES ('Difficile');

INSERT INTO `receipe` (`time_needed`, `number_of_persons`, `dessert_id`, `difficulty_id`) VALUES ('25 minutes', '6', '1', '2');
INSERT INTO `receipe` (`time_needed`, `number_of_persons`, `Dessert_id`, `Difficulty_id`) VALUES ('55 minutes ', '6', '2', '2');
INSERT INTO `receipe` (`time_needed`, `number_of_persons`, `Dessert_id`, `Difficulty_id`) VALUES ('15 minutes', '6', '3', '1');
INSERT INTO `receipe` (`time_needed`, `number_of_persons`, `Dessert_id`, `Difficulty_id`) VALUES ('35 minutes', '6', '4', '1');
INSERT INTO `receipe` (`time_needed`, `number_of_persons`, `Dessert_id`, `Difficulty_id`) VALUES ('1 heure et 5 minutes', '6', '5', '1');
INSERT INTO `receipe` (`time_needed`, `number_of_persons`, `Dessert_id`, `Difficulty_id`) VALUES ('1 heure et 30 minutes', '6', '6', '3');
INSERT INTO `receipe` (`time_needed`, `number_of_persons`, `Dessert_id`, `Difficulty_id`) VALUES ('25 minutes', '6', '7', '1');
INSERT INTO `receipe` (`time_needed`, `number_of_persons`, `Dessert_id`, `Difficulty_id`) VALUES ('50 minutes', '6', '8', '2');
INSERT INTO `receipe` (`time_needed`, `number_of_persons`, `Dessert_id`, `Difficulty_id`) VALUES ('1 heure et 30 minutes', '6', '9', '3');
INSERT INTO `receipe` (`time_needed`, `number_of_persons`, `Dessert_id`, `Difficulty_id`) VALUES ('55 minutes', '6', '10', '1');
INSERT INTO `receipe` (`time_needed`, `number_of_persons`, `Dessert_id`, `Difficulty_id`) VALUES ('1 heure et 15 minutes', '6', '11', '4');
INSERT INTO `receipe` (`time_needed`, `number_of_persons`, `Dessert_id`, `Difficulty_id`) VALUES ('45 minutes', '6', '12', '1');
INSERT INTO `receipe` (`time_needed`, `number_of_persons`, `Dessert_id`, `Difficulty_id`) VALUES ('50 minutes', '6', '13', '2');
INSERT INTO `receipe` (`time_needed`, `number_of_persons`, `Dessert_id`, `Difficulty_id`) VALUES ('1 heure', '6', '14', '1');
INSERT INTO `receipe` (`time_needed`, `number_of_persons`, `Dessert_id`, `Difficulty_id`) VALUES ('1 heure et 5 minutes', '6', '15', '1');


INSERT INTO `step` (`description`, `receipe_id`) VALUES ("1.  Écraser en miettes d’1 paquet de petit beurre et les mélanger avec 100g de beurre doux.", "1");
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("2.  Disposer la préparation au fond d'un moule à fond amovible. Bien tasser.", "1");
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("3.  Préparer le caramel beurre salé:", "1");
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("4.  Faire chauffer 5 cuillères à soupe de sucre dans une casserole, dès que le caramel colore, y ajouter les 50g de beurre salé et les 20cl de crème liquide préalablement chauffée dans une casserole.", '1'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("5.  Disposer le caramel beurre salé refroidi sur le gâteau.", '1'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("6.  Couper 3 bananes en rondelles et les disposer sur le caramel.", '1'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("7.  Battre 2 blancs d’œufs en neige ferme.", '1'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("8.  Mélanger 250g de mascarpone avec '1' jaune d'œuf, ajouter 3 cuillères à soupe de sucre.", '1'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("9.  Ajouter délicatement à cette préparation les blancs en neige.", '1'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("10. Mettre le tout dans une poche à douille et disposer sur les bananes en formant des petits dômes.", '1'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("11. Réserver au frais.", '1');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("12. Au moment de servir saupoudrer de cacao amer pour la décoration.", '1'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("13. A faire 4 à 6 heures à l'avance.", '1');

INSERT INTO `step` (`description`, `receipe_id`) VALUES ("1.  Faire bouillir 90cl de lait avec 1 gousse de vanille fendue dans la longueur et en ayant préalablement gratté la gousse.", '2'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("2.  Laisser infuser la préparation 5 minutes, puis retirer la gousse.", '2'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("3.  Séparer les jaunes de 6 œufs et les battre avec 80 g de sucre.", '2'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("4.  Ajouter le lait chaud puis remettre sur feu doux pour faire épaissir le mélange. Agiter sans arrêt avec une cuillère en bois et sans faire bouillir la crème.", '2'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("5.  La crème est prise lorsque la mousse blanche en surface disparaît.", '2'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("6.  Mettre au réfrigérateur une fois la préparation refroidie.", '2'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("7.  Dans une grande casserole, mettre 2 l d'eau à bouillir.", '2'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("8.  Monter les blancs en neige avec une pincée de sel et ajouter doucement 30 g de sucre.", '2'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("9.  Former des boules de blancs d'œuf avec deux cuillères à soupe et les faire cuire toutes les faces dans de l'eau bouillante.", '2'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("10. Compter 1 min et égoutter sur papier absorbant.", '2'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("11. Dorer 45g d’amandes à la poêle.", '2'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("12. Faire un caramel blond avec 90g de sucre en morceaux, un filet de citron et 2 cuillères à soupe d'eau.", '2'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("13. Mettre la crème dans un plat creux. Y déposer les blancs puis décorer avec des filets de caramel et un peu d'amandes.", '2'); 

INSERT INTO `step` (`description`, `receipe_id`) VALUES ("1.  Séparer les blancs des jaunes de 5 oeufs.", '3');  
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("2.  Mélanger les jaunes avec 150g de sucre roux et 1,5 sachet de sucre vanillé.", '3'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("3.  Ajouter 375g de mascarpone au fouet.", '3'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("4.  Monter les blancs en neige et les incorporer délicatement à la spatule au mélange précédent. Réserver.", '3'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("5.  Mouiller 36 biscuits dans le café (environs 75cl de café noir non sucré) rapidement avant d'en tapisser le fond du plat.", '3'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("6.  Recouvrir d'une couche de crème au mascarpone puis répéter l'opération en alternant couche de biscuits et couche de crème en terminant par cette dernière.", '3'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("7.  Saupoudrer de cacao.", '3'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("8.  Mettre au réfrigérateur 4 heures minimum puis déguster frais.", '3'); 

INSERT INTO `step` (`description`, `receipe_id`) VALUES ("1.  Préchauffer le four à 180°C (thermostat 6).", '4'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("2.  Faire fondre 150g de chocolat et 75g de beurre au bain-marie à feu doux, ou au micro-ondes sur le programme 'décongélation'.", '4'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("3.  Pendant ce temps, séparer les jaunes des blancs de 4 œufs.", '4'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("4.  Monter les blancs en neige ferme. Réserver.", '4'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("5.  Quand le mélange chocolat-beurre est bien fondu, ajouter les jaunes d’œufs et fouetter.", '4'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("6.  Incorporer 75g de sucre et 3 cuillères à soupe de farine, puis ajouter les blancs d’œufs sans les casser.", '4'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("7.  Beurrer et fariner un moule à manquer et y verser la pâte à gâteau.", '4'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("8.  Enfourner pendant 20 minutes.", '4'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("9.  Quand le gâteau est cuit, le laisser refroidir avant de le démouler.", '4'); 

INSERT INTO `step` (`description`, `receipe_id`) VALUES ("1.  Mettre 1 pâte feuilletée dans un plat à tarte, la piquer avec une fourchette, garnir avec 5 pommes coupées en morceaux.", '5'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("2.  Mélanger 90g sucre, 2 œufs, 60g de beurre fondu et verser sur la tarte.", '5'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("3.  Enfournez, thermostat 6-7 ( 200°) pendant 35 minutes environ.", '5'); 

INSERT INTO `step` (`description`, `receipe_id`) VALUES ("1.  Faire fondre 225g de beurre au bain marie.", '6'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("2.  Mélanger 450g de biscuits (types Lu) écrasés et le beurre fondu.", '6'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("3.  Tasser cette préparation dans le fond d'un petit moule et mettre au réfrigérateur.", '6'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("4.  Mélanger 9 œufs à 15 petits suisses un par un.", '6'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("5.  Battre et ajouter 1,5 cuillère à soupe de jus de citron et 150g de sucre.", '6'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("6.  Attendre 2 heures.", '6'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("7.  Cuire à 180°C (thermostat 6) durant 1 heure.", '6'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("8.  Ajouter du coulis de fruits rouges sur le tout et démouler.", '6'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("9.  Mettre au à nouveau au réfrigérateur.", '6'); 

INSERT INTO `step` (`description`, `receipe_id`) VALUES ("1.  Mélanger 100g de sucre avec 100g de farine. Y ajouter 3 œufs. Mélanger le tout puis y incorporer un paquet de levure.", '7'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("2.  Verser la préparation dans un moule à baba beurré au préalable.", '7'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("3.  Mettre à four chaud (déjà chauffé depuis 15 minutes environ) à 200°C durant 15 mn (la cuisson est très importante normalement il ne faut pas dépasser ces 15 minutes !!!).", '7'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("4.  Piquer avec un couteau pour voir si la pâte est bien cuite.", '7'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("5.  Pendant la cuisson du baba : verser dans une casserole 70g de sucre avec 500ml d’eau et dès les premiers bouillons y verser 250ml de rhum et éteindre le feu.", '7'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("6.  Lorsque le baba est sorti du four, il ne faut surtout pas le démouler, y verser (encore chaud) le sirop tout autour. Il faut bien l'imbiber partout.", '7'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("7.  Lorsque le baba est froid le mettre au frigo au moins 10 heures.", '7'); 

INSERT INTO `step` (`description`, `receipe_id`) VALUES ("1.  Déroulez la pâte brisée avec sa feuille de cuisson dans un moule à tarte. Faites cuire à blanc 20 minutes à 180°C (thermostat 6).", '8');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("2.  Pendant ce temps, travaillez 1 œuf entier et 2 jaunes et 80g de sucre. Incorporez 30g de farine et 500ml de lait chaud. Faites épaissir le mélange dans une casserole à feux doux en tournant avec une cuillère en bois.", '8');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("3.  Retirez du feu dès que la crème est prise. Ajoutez 1 sachet de sucre vanillé.", '8');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("4.  Sortez le fond de tarte du four. Laissez refroidir. Versez-y la crème.", '8');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("5.  Disposez 300g de framboises en cercle sur la crème, pour faire une belle présentation.", '8');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("6.  Nappez de gelée de framboises liquéfiée avec 2 cuillerées d'eau.", '8');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("7.  Servez froid...", 8);

INSERT INTO `step` (`description`, `receipe_id`) VALUES ("1.  Pour la pâte à choux:", 9);
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("2.  Préchauffer le four à 210°C (Thermostat 7).", '9');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("3.  Mélanger 1 pincée de sel, 1 cuillère à soupe de sucre, 75g de beurre et 25cl d’eau dans une casserole, et faire bouillir.", '9');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("4.  Intégrer 150g farine, et remuer jusqu'à l'obtention d'une pâte compacte. La travailler jusqu'à ce qu'elle soit suffisamment ferme", '9');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("5.  Intégrer 4 œufs, un à un en veillant à bien mélanger entre chaque œuf.", '9');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("6.  Travailler la pâte afin de la rendre ferme.", '9');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("7.  Sur un plaque allant au four préalablement huilée, répartir à l'aide de la poche à douille une dizaine de boudins de pâte de 15 cm de long environ.", '9');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("8.  Badigeonner avec 1 jaune d'œuf pour que la pâte soit dorée à la cuisson .", '9');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("9.  Faire cuire 25 min à four chaud et laisser reposer 10 min, four éteint, pour éviter que les choux ou les éclairs ne dégonflent.", '9');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("10. Pour la crème:", '9');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("11. Faire fondre 60 g de chocolat cassé en morceaux dans 30cl de lait, à feu doux.", '9');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("12. Dans un bol, fouetter 1 œuf, 2 jaunes d’œufs et 3 cuillères à soupe de sucre jusqu'à ce que le mélange soit mousseux.", '9');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("13. Ajouter 2 cuillères à soupe de farine et verser dans le lait chocolaté.", '9');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("14. Faire épaissir sans cesser de remuer.", '9');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("15. Hors du feu, intégrer 20 g de beurre. Laisser refroidir.", '9');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("16. Garnir de cette crème les éclairs coupés en 2 dans le sens de la longueur et faire fondre au bain-marie 150g de chocolat et 30g beurre.", '9');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("17. Napper le dessus des éclairs. Laisser durcir le glaçage avant de déguster.", '9');

INSERT INTO `step` (`description`, `receipe_id`) VALUES ("1.  Pour la pâte sablée : mettre le four à préchauffer à 180°C (thermostat 6).", '10');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("2.  Fouetter 2  jaunes d'œuf avec 70 g de sucre et 2 cuillères d'eau pour faire mousser.", '10');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("3.  Mélanger au doigt 250g de farine et 125g de beurre coupé en petits cubes pour obtenir une consistance sableuse et afin que tout le beurre soit absorbé (il faut faire vite pour que le mélange ne ramollisse pas trop).", '10');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("4.  Verser au milieu de ce 'sable' le mélange liquide.", '10');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("5.  Former une boule avec les  de la main.", '10');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("6.  Foncer un moule de 25 cm de diamètre avec la pâte sablée puis la recouvrir de papier sulfurisé et de haricots secs.", '10'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("7.  Cuire à blanc 20 à 25 minutes (NB après baisser le four à 120°C/150°C environ pour la meringue).", '10');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("8.  Pour la crème au citron : laver 4 citrons de taille moyen et en râper deux afin de récupérer le zeste.", '10');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("9.  Mettre les zestes très fins dans une casserole avec le jus des citrons, 150g de sucre et 1 cuillère à soupe de Maïzena.", '10');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("10. Remuer et commencer à faire chauffer à feux doux.", '10');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("11. Battre 3 œufs dans un récipient, incorporer tout en remuant le jus de citron, le sucre, la Maïzena et les zestes.", '10');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("12. Mettre à feu vif et continuer à remuer à l'aide d'un fouet. Le mélange va commencer à s'épaissir. Veiller à toujours remuer lorsque les œufs sont ajoutés car la crème de citron pourrait brûler.", '10');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("13. Ôter du feu et verser l'appareil sur le fond de tarte cuit.", '10');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("14. Laisser refroidir.", '10');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("15. Terminons par la meringue : monter 2 blancs en neige avec une pincée de sel.", '10');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("16. Quand ils commencent à être fermes, ajouter 100g de sucre glace puis ½ cuillère à café de levure. Fouetter jusqu'à ce que la neige soit ferme.", '10');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("17. Recouvrir la crème au citron de meringue puis enfourner la tarte à 120°C/150°C jusqu’à ce que la meringue dore (environ 10 minutes).", '10');

INSERT INTO `step` (`description`, `receipe_id`) VALUES ("1.  Faites d’abord la crème. Portez 25cl de lait à ébullition. Fouettez 3 jaunes avec 60g de sucre jusqu’à ce qu’ils blanchissent, incorporez 20g de Maïzena. Versez dessus le lait bouillant en filet en fouettant. Faites épaissir sur feu moyen en remuant jusqu’à l’ébullition. Laissez refroidir.", '11');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("2.  Travaillez 125g de beurre en pommade. Incorporez la crème pâtissière et 115g de praliné, en fouettant afin de bien aérer la masse.", '11');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("3.  Allumez le four à 180°C . Couvrez la plaque de papier sulfurisé. Portez 12,5cl d’eau et de le lait à ébullition avec 55g de beurre, 10g de sucre et une pincée de sel. Ajoutez 50g de farine et 20g de Maïzena d’un coup. Remuez vivement jusqu’à ce que la pâte se détache des parois. Eteignez le feu, incorporez 2 oeufs un à un en fouettant avec vigueur. Cessez de fouetter quand la pâte est lisse.", '11');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("4.  Faites un cercle de pâte de 20 cm sur la plaque avec une poche à douille. Formez un second cercle dessus puis un troisième. Décorez d’amandes.", '11');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("5.  Faites dorer 30 mn au four. Laissez refroidir au four éteint, porte entrouverte. Tranchez la couronne dans l’épaisseur.",  '11');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("6.  Garnissez le bas de crème, remettez le couvercle et poudrez de sucre glace.", '11');

INSERT INTO `step` (`description`, `receipe_id`) VALUES ("1.  Préchauffer votre four à thermostat 8.", "12");
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("2.  Éplucher, épépiner et couper 1kg de pommes en gros morceaux. Les faire réduire à feu fort 2 mn avec une cuillerée à soupe d'eau puis maintenir la cuisson à feu doux pendant 7 à 8 mn.", "12");
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("3.  Écraser les derniers gros morceaux de pommes à la fourchette. Mélanger les pommes avec 125 g de sucre et 1/2 cuillère à café de cannelle. Verser ce mélange dans un plat à gratin beurré.", "12");
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("4.  Travailler énergiquement 75g de beurre. Incorporer 125g de sucre et 1 cuillère à café rase de cannelle en poudre, ainsi que 150 g de farine, puis travailler le tout avec les doigts afin d'obtenir un sable grossier.", "12");
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("5.  Répartir sur la compote et cuire au four 25 mn (grille centrale).", "12");

INSERT INTO `step` (`description`, `receipe_id`) VALUES ("1.  Préchauffez Th.6 (180°C).", '13');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("2.  Dans une casserole, faites chauffer 125 ml d'eau, 40 g de beurre, 10 g de sucre et 1 pincée de sel. Versez 80 g de farine et 10g de cacao. Faites déssécher à feu doux environ 1 minute.", '13');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("3.  Hors du feu, ajoutez 2 oeufs un par un. Sur une plaque de four avec un papier sulfurisé beurré, faites des choux soit avec une poche à douille soit avec une cuillerée à café.", '13');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("4.  Faites cuire environ 30 minutes. Faites refroidir.", '13');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("5.  Dans un saladier, cassez 200g de chocolat en morceaux. Faites bouillir 200ml de crème liquide et versez-la sur le chocolat. Couvrez et attendez environ 2 minutes.", '13');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("6.  Coupez le haut des choux, mettez de la glace vanille dans le choux, puis remettez le chapeau. Couvrez de sauce au chocolat.", '13');

INSERT INTO `step` (`description`, `receipe_id`) VALUES ("1.  Préchauffez le four à 200 °C.", '14');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("2.  Faites bouillir 500 ml d'eau et infusez-y 1 sachet de thé Earl Grey. Ôtez le sachet, versez le thé sur 12 pruneaux et laissez mariner 10 min.", '14');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("3.  Égouttez les pruneaux et disposez-les dans un moule à gratin beurré.", '14');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("4.  Mélangez 80g de sucre, 60g de farine et 1 pincée de sel dans un saladier. Ajoutez 3 œufs un à un ainsi que l’arôme vanille et mélangez pour obtenir une crème bien lisse. Incorporez 1/3 de litre de lait et mélangez à nouveau.", '14');
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("5.  Versez la pâte sur les pruneaux et enfournez environ 50 min.", '14');

INSERT INTO `step` (`description`, `receipe_id`) VALUES ("1.  Préchauffer le four à 180°C (thermostat 6).", '15'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("2.  Couper 100g de fraises en petits dés.", '15'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("3.  Faire fondre 100g de beurre.", '15'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("4.  Dans une jatte, battre au fouet 2 œufs et 125g de sucre jusqu'à ce que le mélange devienne mousseux.", '15'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("5.  Ajouter 4cl de lait, 4 cl d'arôme de vanille liquide puis le beurre fondu. Sans cesser de remuer, incorporer 125g de farine et 1 cuillère à café de levure chimique en 4 fois afin d'obtenir un mélange homogène.", '15'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("6.  Délicatement, ajouter les fraises à la préparation.", '15'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("7.  Répartir la pâte dans des moules à cupcakes et mettre au four 20 min.", '15'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("8.  Pour une cuisson optimale, toucher du bout des doigts la surface bombée elle doit reprendre sa forme initiale ensuite. Le 'dôme' doit être doré mais pas craquelé.", '15'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("9.  Laisser refroidir.", '15'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("10. Dans un bol, fouetter 150g de mascarpone, 40g de sucre glace et 2cl d’arome vanille liquide. Terminer par l'ajout de crème fraîche jusqu'à ce que le mélange devienne onctueux et facile à travailler.", '15'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("11. Remplir une poche à douille avec cette préparation puis décorer vos cupcakes totalement refroidis.", '15'); 
INSERT INTO `step` (`description`, `receipe_id`) VALUES ("12. Décorer de perles et de copeaux de chocolat avant de laisser le glaçage prendre de la consistance au réfrigérateur.", '15'); 


INSERT INTO `ingredient` (`name`, `photo`) VALUES ('Banane', 'https://img-3.journaldesfemmes.fr/dZMGY3kjaLpXk883IjnEf7BOZlc=/910x607/smart/d47b1bd18da64f2a94a7ee7286be5ee9/ccmcms-jdf/10662309.jpg');
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Œufs", "https://observatoireprevention.org/wp-content/uploads/2019/09/shutterstock_496251349.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Lait", "https://fondationolo.ca/wp-content/uploads/2017/03/fondation-olo-infographie-lait-v2.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Sucre", "https://audriveenpot.fr/923-large_default/sucre-cristallise-betterave-bio-500g.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Speculoos", "https://static.750g.com/images/640-420/1b3c49dced85ba7340fa63fa3ae8686f/speculoos-de-belgique.jpeg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Beurre", "https://i-reg.unimedias.fr/sites/art-de-vivre/files/styles/large/public/r30_copeau-beurre_fo.jpg?auto=compress%2Cformat&crop=faces%2Cedges&cs=srgb&fit=crop&h=635&w=900");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Boudoirs", "https://i.pinimg.com/564x/47/54/3c/47543cbd094e96531aa72f3005f2bc6d.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Crème", "https://producteurslaitiersducanada.ca/sites/default/files/styles/recipe_image/public/image_file_browser/conso_recipe/creme-fraiche.jpg.jpeg?itok=rY9Ns92o");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Fromage Blanc", "https://static.750g.com/images/600-400/024e34ebfef04a75a859a7e6be28600d/thinkstockphotos-511805370.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Biscuits", "https://static.greenweez.com/images/products/118000/600/belledonne-biscuits-nappes-chocolat-au-lait-1-5kg.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Lait concentré", "https://static.750g.com/images/600-400/308c3c6afbd2f524ff7596560d5a3203/thinkstockphotos-642266542.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Levure", "https://img-3.journaldesfemmes.fr/rdq8vJl62-j3lh2C-Mr3W2QzeSM=/910x607/smart/b30b76812b8e4234a3817cdd0aaa9594/ccmcms-jdf/15657777.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Cassonade", "https://www.laboetgato.fr/67401-thickbox_default/sucre-cassonade-500-g.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Citron", "https://alsace.nouvellesgastronomiques.com/photo/art/default/45432100-36693657.jpg?v=1588065833");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Liqueur", "https://media.flaschenland.com/ProductImages/500px/40ml_bouteille_apothicaire_1.webp");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Eau", "https://i1.wp.com/oyomy.fr/wp-content/uploads/2016/07/verre-d-eau-pure.jpg?w=460&ssl=1");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Maïzena", "https://img-3.journaldesfemmes.fr/vRrCR3wdrdileIXVqLFr0h-r7eQ=/910x607/smart/e6668d4f722f4f77ba841f7faba331c0/ccmcms-jdf/15613195.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Farine", "https://cuisine-facile.com/images/pages/faire-son-pain-farine.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Chocolat", "https://www.lsa-conso.fr/mediatheque/6/8/0/000362086_5.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Caramel", "https://www.olfastory.com/sites/www.olfastory.com/files/styles/400x400/public/caramel.jpg?itok=BCrZr3Jy");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Framboise", "https://www.notretemps.com/cache/com_zoo_images/e4/framboise02_79051570b64846c016e9c560f4701758.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Fraise", "https://img-3.journaldesfemmes.fr/LFYLLU8JV163I7rcv9-y_SrLuTs=/910x607/smart/e2d84215f5c44c648c3ecdcbf0ac1ccc/ccmcms-jdf/10662418.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Café", "https://www.boutique-artisans-du-monde.com/media/catalog/product/cache/1/small_image/600x600/9df78eab33525d08d6e5fb8d27136e95/c/a/cafe-grains-vrac-bio-equitable.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Pommes", "https://produits.bienmanger.com/35111-0w0h0_Pommes_Story_France_Bio.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Vanille", "https://img-3.journaldesfemmes.fr/SpdYY0aMyVDA04ajWX0rBOD-Zho=/910x607/smart/39dc0212be504e47b46a2decd2cef516/ccmcms-jdf/10661457.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Cacao", "https://www.jeanherve.fr/271-thickbox_default/poudre-de-cacao-bio.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Pralin", "https://img-3.journaldesfemmes.fr/p7TYVpWh-AvDhssIcjWESQExRmQ=/748x499/smart/bb25be0ed98c4731a866a5dada0b5a77/recipe-jdf/392341.jpg");
INSERT INTO `ingredient` (`name`, `photo`) VALUES ("Pruneaux", "https://www.fruitssecsduweb.com/4625-large_default/pruneau-d-agen-igp-denoy-tres-gros-produit-issu-agriculture-biologique-fr-bio-01.jpg");


INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('1', '10');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('1', '6');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('1', '4');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('1', '8');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('1', '1');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('1', '2');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('1', "26");
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('2', '2');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('2', '3');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('2', '25');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('2', '4');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('2', '14');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('3', '2');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('3', '13');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('3', '8');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('3', '7');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('3', '23');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('3', '26');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('4', '19');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('4', '6');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('4', '4');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('4', '2');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('4', '18');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('5', '4');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('5', '2');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('5', '6');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('5', '24');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('6', '10');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('6', '4');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('6', '6');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('6', '8');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('6', '14');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('6', '2');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('6', '21');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('6', '22');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('7', '4');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('7', '18');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('7', '2');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('7', '12');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('7', '15');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('7', '16');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('8', '21');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('8', '2');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('8', '4');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('8', '18');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('8', '3');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('8', '25');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('9', '18');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('9', '16');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('9', '6');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('9', '4');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('9', '2');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('9', '3');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('9', '19');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('10', '18');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('10', '6');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('10', '4');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('10', '2');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('10', '16');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('10', '14');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('10', '17');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('10', '12');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('11', '16');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('11', '4');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('11', '6');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('11', '4');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('11', '18');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('11', '2');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('11', '17');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('11', '27');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('12', '24');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('12', '18');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('12', '6');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('12', '4');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('13', '8');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('13', '19');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('13', '26');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('13', '16');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('13', '2');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('13', '18');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('13', '6');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('13', '4');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('14', '28');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('14', '4');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('14', '2');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('14', '18');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('14', '3');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('14', '6');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('15', '4');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('15', '18');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('15', '6');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('15', '2');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('15', '22');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('15', '12');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('15', '25');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('15', '3');
INSERT INTO `receipe_has_ingredient` (`receipe_id`, `ingredient_id`) VALUES ('15', '8');

